* Introduction
Herbert Alexander Simon was born in Milwaukee, Wisconsin on June 15, 1916. 

He is an American political scientist, economist, sociologist, 
psychologist, and computer scientist whose research ranged across 
the fields of cognitive psychology, cognitive science, computer 
science, public administration, economics, management, philosophy 
of science, sociology, and political science, unified by studies of 
decision-making. 

Simon was among the pioneers of several of today's 
important scientific domains, including artificial intelligence, 
information processing, decision-making, problem-solving, 
organization theory, complex systems, and computer simulation of 
scientific discovery.

** Career
In 1933, Simon entered the University of Chicago, and studied the 
social sciences and mathematics. Simon received 
both his B.A. (1936) and his Ph.D. (1943) in political science, 
from the University of Chicago. Simon was invited to be a research 
assistant for Clarence Ridley, with whom he coauthored the book, 
Measuring Municipal Activities, in 1938.

After graduating with his undergraduate degree, Simon obtained a 
research assistantship in municipal administration which turned 
into a directorship at the University of California, Berkeley.

From 1942 to 1949, Simon was a professor of political science 
and also served as department chairman at Illinois Institute of 
Technology in Chicago.

From 1949 to 2001, Simon was a faculty at Carnegie Mellon. 
In 1949, Simon became a professor of administration and chairman 
of the Department of Industrial Management at Carnegie Tech.
He also taught psychology and computer science in the same university.

* Works
Simon became best known for his theory of corporate decision in 
his book Administrative Behavior. In this book he based his 
concepts with an approach that recognized multiple factors that 
contribute to decision making.

Herbert Simon has made a great number of profound and in depth 
contributions to both economic analysis and applications. 

Because of this, his work can be found in a number of economic 
literary works, making contributions to areas such as mathematical 
economics including theorem, human rationality, behavioral study of 
firms, theory of casual ordering, and the analysis of the 
identification problem in econometrics.

** Contributions to today's technology
Simon was a pioneer in the field of artificial intelligence, 
creating with Allen Newell the Logic Theory Machine (1956) and 
the General Problem Solver (GPS) (1957) programs.

Simon along with Allen Newel developed a theory for the simulation of
human problem solving behavior using production rules.

Simon developed the Elementary Perceiver and Memorizer(EPAM) theory,
one of the first theories of learning to be implemented as a 
computer program. EPAM was able to explain a large number of 
phenomena in the field of verbal learning.

Simon has been credited for revolutionary changes in microeconomics. 
He is responsible for the concept of organizational decision-making. 
He also was the first to discuss this concept in terms of uncertainty 
i.e. it is impossible to have perfect and complete information at 
any given time to make a decision.

* Honors and Prizes
He has received many top-level honors in life. These include:
**** ACM's Turing Award
**** Becoming a fellow of the American Academy of Arts and Sciences
**** Election to the National Academy of Sciences in 1967
**** APA Award for Distinguished Scientific Contributions to Psychology (1969)
**** Nobel Memorial Prize in Economics
**** APA's Award for Outstanding Lifetime Contributions to Psychology (1993)
**** IJCAI Award for Research Excellence
**** Honorary doctorate, Lund School of Economics and Management, 1968.
**** Honorary degree, University of Pavia, 1988.
**** Honorary Doctor of Laws (LL.D.) degree from Harvard University in 1990.
**** Honorary degree, University of Buenos Aires, 1999
